// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQmUCRjEHgmQZVjBSKBoD9z1FpXxrmTQ',
    appId: '1:558843228440:web:c4c9254d521c53fba56e6d',
    messagingSenderId: '558843228440',
    projectId: 'class16-f9a31',
    authDomain: 'class16-f9a31.firebaseapp.com',
    databaseURL: 'https://class16-f9a31-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class16-f9a31.appspot.com',
    measurementId: 'G-7HLMYLEF73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1oN4Bw5egIrWLMsZrY0ZJ-etOeSjvCEk',
    appId: '1:558843228440:android:557cb52cd81f67c0a56e6d',
    messagingSenderId: '558843228440',
    projectId: 'class16-f9a31',
    databaseURL: 'https://class16-f9a31-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class16-f9a31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhXzJxzzkuD4M5qmYn6PoP8_0fUM4R74',
    appId: '1:558843228440:ios:2c20091a17900e79a56e6d',
    messagingSenderId: '558843228440',
    projectId: 'class16-f9a31',
    databaseURL: 'https://class16-f9a31-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class16-f9a31.appspot.com',
    iosBundleId: 'com.example.class16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhXzJxzzkuD4M5qmYn6PoP8_0fUM4R74',
    appId: '1:558843228440:ios:f2340dc94b43e37ba56e6d',
    messagingSenderId: '558843228440',
    projectId: 'class16-f9a31',
    databaseURL: 'https://class16-f9a31-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'class16-f9a31.appspot.com',
    iosBundleId: 'com.example.class16.RunnerTests',
  );
}
