// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKEf5R22S3d2I_7KZyecgtzQVwz4LXdgY',
    appId: '1:557210785560:web:bb65759e665e917b0db06d',
    messagingSenderId: '557210785560',
    projectId: 'fir-123-a5047',
    authDomain: 'fir-123-a5047.firebaseapp.com',
    storageBucket: 'fir-123-a5047.appspot.com',
    measurementId: 'G-8R8B38YYTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsw00WnLk6vHnqD2Bh-qyRTMlc2kgSl8M',
    appId: '1:557210785560:android:92848cc6745723480db06d',
    messagingSenderId: '557210785560',
    projectId: 'fir-123-a5047',
    storageBucket: 'fir-123-a5047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbd2Cj52j6jJyLg3o7Eqr76BWdWD95PPc',
    appId: '1:557210785560:ios:b1b0a73eb41969330db06d',
    messagingSenderId: '557210785560',
    projectId: 'fir-123-a5047',
    storageBucket: 'fir-123-a5047.appspot.com',
    iosBundleId: 'com.example.firebase123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbd2Cj52j6jJyLg3o7Eqr76BWdWD95PPc',
    appId: '1:557210785560:ios:d7bf521364239aee0db06d',
    messagingSenderId: '557210785560',
    projectId: 'fir-123-a5047',
    storageBucket: 'fir-123-a5047.appspot.com',
    iosBundleId: 'com.example.firebase123.RunnerTests',
  );
}
