// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwmaGzge6K10Yz2bt4ZBkOHfKAxgnJH8',
    appId: '1:201672904831:web:40bdca410cd178ca9eaf4a',
    messagingSenderId: '201672904831',
    projectId: 'socialmedia1-61656',
    authDomain: 'socialmedia1-61656.firebaseapp.com',
    databaseURL: 'https://socialmedia1-61656-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia1-61656.appspot.com',
    measurementId: 'G-FH1MDQFL6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeEjiOyihot-kaxdg_6APUIh7LKyx8uXU',
    appId: '1:201672904831:android:d7e750eaebfbce4b9eaf4a',
    messagingSenderId: '201672904831',
    projectId: 'socialmedia1-61656',
    databaseURL: 'https://socialmedia1-61656-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia1-61656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbAlXJ6kEq7yaMTIixb9v6Ojpf0SIdus',
    appId: '1:201672904831:ios:5f3090df72796f289eaf4a',
    messagingSenderId: '201672904831',
    projectId: 'socialmedia1-61656',
    databaseURL: 'https://socialmedia1-61656-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia1-61656.appspot.com',
    iosBundleId: 'com.example.socialmedia1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbAlXJ6kEq7yaMTIixb9v6Ojpf0SIdus',
    appId: '1:201672904831:ios:3cc914a5ccf6ec609eaf4a',
    messagingSenderId: '201672904831',
    projectId: 'socialmedia1-61656',
    databaseURL: 'https://socialmedia1-61656-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmedia1-61656.appspot.com',
    iosBundleId: 'com.example.socialmedia1.RunnerTests',
  );
}
