// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6yart4PeNsqJJ4iQG-n_VLsNkdtni8k',
    appId: '1:503219129293:web:18fd676fd5240251d6d284',
    messagingSenderId: '503219129293',
    projectId: 'chatapps-6f296',
    authDomain: 'chatapps-6f296.firebaseapp.com',
    storageBucket: 'chatapps-6f296.appspot.com',
    measurementId: 'G-TXV13PYC3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTRHkFtSUUnRURq85omS5XGuCj8CmLOk',
    appId: '1:503219129293:android:4c85a8ece3896c86d6d284',
    messagingSenderId: '503219129293',
    projectId: 'chatapps-6f296',
    storageBucket: 'chatapps-6f296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAFknm5CpXUB6-EBhYOVf-wLD_egS-_X0',
    appId: '1:503219129293:ios:60aa625804fbc9dfd6d284',
    messagingSenderId: '503219129293',
    projectId: 'chatapps-6f296',
    storageBucket: 'chatapps-6f296.appspot.com',
    iosBundleId: 'com.example.chatapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAFknm5CpXUB6-EBhYOVf-wLD_egS-_X0',
    appId: '1:503219129293:ios:98f70fb38ba791b5d6d284',
    messagingSenderId: '503219129293',
    projectId: 'chatapps-6f296',
    storageBucket: 'chatapps-6f296.appspot.com',
    iosBundleId: 'com.example.chatapps.RunnerTests',
  );
}
