// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5VL7uveOxRxJ-OeQhVPFe0a569rCeAE',
    appId: '1:719626117212:web:296fea7e6d742fbc67c699',
    messagingSenderId: '719626117212',
    projectId: 'keeps-6f913',
    authDomain: 'keeps-6f913.firebaseapp.com',
    storageBucket: 'keeps-6f913.appspot.com',
    measurementId: 'G-0P3PCFEQM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx7fMSdQ8rTUNRWjKQXwN7zjEcxuGmq3s',
    appId: '1:719626117212:android:eaa1526bcbfb6e7e67c699',
    messagingSenderId: '719626117212',
    projectId: 'keeps-6f913',
    storageBucket: 'keeps-6f913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW3E5at2nFl0NdSzVzkdShELwgIsyzuYw',
    appId: '1:719626117212:ios:bb5b05f8dbeaa22167c699',
    messagingSenderId: '719626117212',
    projectId: 'keeps-6f913',
    storageBucket: 'keeps-6f913.appspot.com',
    iosBundleId: 'com.example.keeps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW3E5at2nFl0NdSzVzkdShELwgIsyzuYw',
    appId: '1:719626117212:ios:7324f7c6db6eb04167c699',
    messagingSenderId: '719626117212',
    projectId: 'keeps-6f913',
    storageBucket: 'keeps-6f913.appspot.com',
    iosBundleId: 'com.example.keeps.RunnerTests',
  );
}
